version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    # environment:
    #   - GOOGLE_APPLICATION_CREDENTIALS=/Users/esther/DevOps/Bootcamp/MODULO4-Docker_k8s/practica_contenedores/flask/key.json  
    # logging:
    #   driver: gcplogs 
    #   options:
    #     gcp-project: "kainight"               
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
    expose:
      - 6379

