apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis
  name: redis
  namespace: counter-flask  
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
