apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: redis
  name: redis
  namespace: counter-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  strategy: {}
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - image: redis
        name: redis
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: REDIS_HOST
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: REDIS_PASSWORD
        resources:
          requests:
            memory: 228Mi
            cpu: 200m
          limits:
            memory: 356Mi
            cpu: 300m
        volumeMounts:
        - name: data
          mountPath: /data 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pv-claim
status: {}
  